name = "flow-app"
account_id = "cb42eff93988888f69b2643fa2d188e5"
compatibility_date = "2025-06-10"

# Tell Wrangler where your Functions are
[functions]
  # Any TS/JS files under functions/ will be served under /api/*
  directory = "functions"

# Bind your KV namespace
[[kv_namespaces]]
  binding = "FLOW_KV"
  id = "caf0cbf0b6c641829984345e04f3beb2"