name = "flow-app"
account_id = "30178101df3777d9213a05927ee021f9"
compatibility_date = "2025-06-10"

# Tell Pages where your static build lives
[build]
command = "npm run build"
directory = "dist"

# Tell Wrangler where your Functions are
[functions]
  # Any TS/JS files under functions/ will be served under /api/*
  directory = "functions"

# Bind your KV namespace
[[kv_namespaces]]
  binding = "FLOW_KV"
  id = "6637815cef4d46b592f659281b22836f"